name: "Build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Install ltext
      run: sudo snap install --edge ltext
    - name: Install Node.js Dependencies
      run: npm ci
    - name: Build
      run: nix-shell --command ./build.sh
